[package]
name = "streamchat"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
twitchchat = "0.6.3"

[dependencies.serde]
version = "1.0.92"
features = ["derive"]
