[package]
name = "streamchatc"
version = "0.1.1"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
streamchat = { path = "../streamchat" }
twitchchat = "0.4.3"
gumdrop = "0.5.0"
gumdrop_derive = "0.5.0"
crossterm = "0.9.3"
unicode-width = "0.1.5"
serde_json = "1.0.39"

[dependencies.serde]
version = "1.0.90"
features = ["derive"]

[dependencies.configurable]
git = "https://github.com/museun/configurable"
version = "0.3.1"
